# Generated by Django 5.2.7 on 2026-03-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetrack',
            name='email_count',
            field=models.IntegerField(default=0),
        ),
    ]
